data_root_dir: /large_experiments/opencatalyst/foundation_models/benchmark
omol_data_root_dir: /checkpoint/ericqu/omol/omol25_evaluation_inputs_250915
omol_s2ef_data_dir: /checkpoint/ericqu/omol
checkpoint_root_dir: /large_experiments/opencatalyst/foundation_models/checkpoints/uma
run_dir: /checkpoint/ericqu/ESCAIPRUNDIR
account: null
partition: scavenge
qos: null
mode: SLURM
device: CUDA
debug: False
mem_gb: 256
dataloader_workers: 8
ranks_per_node: 8
additional_parameters:
  constraint: "volta32gb"
