model: escnmd_backbone_lr

hidden_channels_lr: 32
heisenberg_tf: true
latent_charge_tf: true

max_num_elements: 100
sphere_channels: 128
lmax: 2
mmax: 2
otf_graph: False
use_pbc: True
use_pbc_single: True
edge_channels: 128
distance_function: gaussian
num_distance_basis: 64
regress_forces: True
regress_stress: False
direct_forces: True
num_layers: 4
hidden_channels: 128
norm_type: rms_norm_sh
act_type: gate
ff_type: spectral
chg_spin_emb_type: "rand_emb"
cs_emb_grad: True
dataset_list: ${dataset_list}
