oc20_elem_refs:
- 0.0
- -0.16141512
- 0.03262098
- -0.04787699
- -0.06299825
- -0.14979306
- -0.11657468
- -0.10862579
- -0.10298174
- -0.03420248
- 0.02673997
- -0.03729558
- 0.00515243
- -0.07535697
- -0.13663351
- -0.12922852
- -0.11796547
- -0.07802946
- -0.00672682
- -0.04089589
- -0.00024177
- -1.74545186
- -1.54220241
- -1.0934019
- -1.16168372
- -1.23073475
- -0.78852824
- -0.71851599
- -0.52465053
- -0.02692092
- -0.00317922
- -0.06266862
- -0.10835274
- -0.12394474
- -0.11351727
- -0.07455817
- -0.00258354
- -0.04111325
- -0.02090265
- -1.89306078
- -1.30591887
- -0.63320009
- -0.26230344
- -0.2633669
- -0.5160055
- -0.95950798
- -1.45589361
- -0.0429969
- -0.00026949
- -0.05925609
- -0.09734631
- -0.12406852
- -0.11427538
- -0.07021442
- 0.01091345
- -0.05305289
- -0.02427209
- -0.19975668
- -1.71692859
- -1.53677781
- -3.89987009
- -10.70940462
- -6.71693816
- -0.28102249
- -8.86944824
- -7.95762687
- -7.13041437
- -6.64620014
- -5.11482482
- -4.42548227
- 0.00848295
- -0.06956227
- -2.6748853
- -2.21153293
- -1.67367741
- -1.07636151
- -0.79009981
- -0.16387243
- -0.18164401
- -0.04122529
- -0.00041833
- -0.05259382
- -0.0934314
- -0.11023834
- -0.10039175
- -0.06069209
- 0.01790437
- -0.04694024
- 0.00334084
- -0.06030621
- -0.58793619
- -1.27821808
- -4.97483577
- -5.66985655
- -8.43154622
- -11.15001317
- -12.95770812
- 0.0
- -14.47602729
- 0.0
odac_elem_refs:
- 0.0
- -1.11737936
- -0.00011835
- -0.2941727
- -0.03868426
- -0.34862832
- -1.31552566
- -3.12457285
- -1.6052078
- -0.49653389
- -0.01137327
- -0.21957281
- -0.0008343
- -0.2750172
- -0.88417265
- -1.887378
- -0.94903558
- -0.31628167
- -0.02014536
- -0.15901053
- -0.00731884
- -1.96521355
- -1.89045209
- -2.53057428
- -5.43600675
- -5.09739336
- -3.03088746
- -1.23786562
- -0.40650749
- -0.2416017
- -0.01139188
- -0.26282496
- -0.82446455
- -1.70237206
- -0.84245376
- -0.28544892
- -0.02239991
- -0.14115912
- -0.02840799
- -2.09540994
- -1.85863996
- -1.12257399
- -4.32965355
- -3.30670045
- -1.19460755
- -1.26257601
- -1.46832888
- -0.19779414
- -0.0144274
- -0.23668767
- -0.70836953
- -1.43186113
- -0.71701186
- -0.24883129
- -0.01118184
- -0.13173447
- -0.0318395
- -0.41195547
- -1.23134873
- -2.03082996
- 0.1375954
- -5.45866275
- -7.59139905
- -5.99965965
- -8.43495767
- -2.6578407
- -7.77349787
- -5.30762201
- -5.15109657
- -4.41466995
- -0.02995219
- -0.2544495
- -3.23821202
- -3.45887214
- -4.53635003
- -4.60979468
- -2.90707964
- -1.28286153
- -0.57716664
- -0.18337108
- -0.01135944
- -0.22045398
- -0.66150479
- -1.32506342
- -0.66500178
- -0.22643927
- -0.00728197
- -0.11208472
- -0.00757856
- -0.21798637
- -0.91078787
- -1.78187161
- -3.89912261
- -3.94192659
- -7.59026042
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
omat_elem_refs:
- 0.0
- -1.11700253
- 0.00079886
- -0.29731164
- -0.04129868
- -0.29106192
- -1.27751531
- -3.12342715
- -1.54797136
- -0.43969356
- -0.01250908
- -0.22855413
- -0.00943179
- -0.21707638
- -0.82619133
- -1.88667434
- -0.89093583
- -0.25816211
- -0.02414768
- -0.17662425
- -0.02568319
- -2.13001165
- -2.38688845
- -3.55934233
- -5.44700879
- -5.14749562
- -3.30662847
- -1.42167737
- -0.63181379
- -0.23449167
- -0.01146636
- -0.21291259
- -0.77939897
- -1.70148487
- -0.78386705
- -0.22690657
- -0.02245409
- -0.16092396
- -0.02798717
- -2.25685695
- -2.23690495
- -2.15347771
- -4.60251809
- -3.36416792
- -2.23062607
- -1.15550917
- -1.47553527
- -0.19918102
- -0.01475888
- -0.19767692
- -0.68005773
- -1.43073368
- -0.65790462
- -0.18915279
- -0.01179476
- -0.13507902
- -0.03056979
- -0.36017439
- -0.86279246
- -0.20573327
- -0.2734463
- -0.20046965
- -0.25444338
- -8.37972664
- -9.58424928
- -0.19466184
- -0.24860115
- -0.19531288
- -0.15401392
- -0.14577898
- -0.19655747
- -0.15645898
- -3.49380556
- -3.5317097
- -4.57108006
- -4.63425205
- -2.88247063
- -1.45679675
- -0.50290184
- -0.18521704
- -0.01123956
- -0.17483649
- -0.63132037
- -1.3248562
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- -0.24135757
- -1.04601971
- -2.04574044
- -3.84544799
- -7.28626119
- -7.3136314
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
omc_elem_refs:
- 0.0
- -0.02831808
- 4.512e-05
- -0.03227157
- -0.03842519
- -0.05829283
- -0.0845041
- -0.08806738
- -0.09021346
- -0.06669846
- -0.01218631
- -0.03650269
- -0.00059093
- -0.05787736
- -0.08730952
- -0.0975534
- -0.09264199
- -0.07124762
- -0.02374602
- -0.05299112
- -0.02631476
- -1.7772147
- -1.25083444
- -0.79579447
- -0.49099317
- -0.31414986
- -0.20292182
- -0.14011632
- -0.09929659
- -0.03771207
- -0.01117902
- -0.06168715
- -0.08873364
- -0.09512942
- -0.09035978
- -0.06910849
- -0.02244872
- -0.05303651
- -0.02871903
- -1.94805417
- -1.33379896
- -0.69169331
- -0.26184306
- -0.20631599
- -0.48251608
- -0.96911893
- -1.47569462
- -0.03845194
- -0.0142445
- -0.07118991
- -0.09940292
- -0.09235056
- -0.08755943
- -0.06544925
- -0.01246646
- -0.04692937
- -0.03225123
- -0.26086039
- -27.20024339
- -0.08412926
- -0.08225924
- -0.07799715
- -0.07806185
- 0.00043759
- -0.07459766
- 0.0
- -0.06842841
- -0.07758266
- -0.07025152
- -0.08055003
- -0.07118177
- -0.07159568
- -2.69202862
- -2.21926765
- -1.679756
- -1.06135075
- -0.4554231
- -0.14488432
- -0.18377098
- -0.03603118
- -0.01076585
- -0.06381411
- -0.0905623
- -0.10095787
- -0.09501217
- -0.0574478
- -0.00599173
- -0.04134751
- -0.0082683
- -0.08704692
- -0.49656425
- -5.24233138
- -2.32542606
- -4.3376616
- -5.96430676
- 0.0
- 0.0
- -0.03842519
- 0.0
- 0.0
oc22_elem_refs:
- 0.0
- -0.01415761
- 0.00190136
- -0.01687239
- -0.04103746
- -0.03177457
- -0.04584783
- -0.04554384
- -1.54692888
- -0.03850826
- -0.01227332
- -0.02186569
- -0.0094005
- -0.03130792
- -0.04870123
- -0.05521285
- -0.89019698
- -0.044664
- -0.02357747
- -0.03725794
- -0.02577522
- -2.02945677
- -2.07240282
- -3.04922796
- -5.44597546
- -5.14654345
- -3.20606092
- -1.69980541
- -0.37671956
- -0.23373115
- -0.0110956
- -0.03508013
- -0.04987832
- -0.05278579
- -0.7833669
- -0.04258381
- -0.02240171
- -0.03676313
- -0.02798498
- -2.2179177
- -2.05341067
- -2.10614213
- -4.60223095
- -2.99793152
- -1.6916374
- -0.99828169
- -1.47553115
- -0.19878999
- -0.01389457
- -0.04465983
- -0.06080418
- -0.04999587
- -0.65676038
- -0.03889693
- -0.01238648
- -0.02910027
- -0.03087012
- 10.54480463
- 12.69487061
- -0.04139441
- -0.03959725
- -0.03453843
- -0.03423227
- -0.12323471
- -3.38885628
- -0.03091119
- -0.0279744
- -0.02978364
- -0.0344141
- -0.02859172
- 0.00129115
- -0.08675705
- -3.29286768
- -3.50518877
- -4.57070495
- -4.63311184
- -2.87196579
- -1.32080363
- -0.1944583
- -0.18479337
- -0.01052316
- -0.0373623
- -0.05187292
- -0.04136443
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- -0.14282605
- -1.00065225
- -1.62627657
- -1.03885412
- -4.72864912
- -6.82839349
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
oc25_elem_refs:
- 0.0
- -0.15225714
- 0.00728714
- -0.03862921
- -0.07065972
- -0.14461594
- -0.08892296
- 0.0
- -0.08867221
- -0.05775523
- -0.00699469
- 0.0
- 0.0
- -0.070819
- -0.11432654
- -0.10100893
- 0.0
- -0.07329019
- -0.0294842
- -0.03262186
- -0.00857281
- -1.72630712
- 0.0
- -0.83051992
- -0.62779218
- -0.29265795
- -0.19746858
- -0.13522504
- -0.09716592
- -0.03632508
- -0.00987175
- -0.05826106
- 0.0
- -0.096307
- 0.0
- -0.07016711
- -0.01864818
- -0.03269462
- -0.02942208
- -1.93616716
- -1.40969053
- 0.0
- -0.2033935
- -0.20616601
- -0.49654327
- -0.97707285
- -1.50232362
- 0.0
- -0.0079154
- -0.05485022
- -0.07578319
- -0.09440058
- -0.08794115
- -0.06584556
- -0.00389639
- -0.04577542
- -0.03245435
- -0.26221596
- -0.73979436
- -1.37696808
- -2.04525248
- 0.0
- -3.37517373
- -0.69674966
- -4.02384014
- -4.17153571
- -3.99913524
- -4.10448817
- 0.0
- -4.18527933
- 0.0
- -0.11761029
- 0.0
- -2.30179053
- -1.71535138
- -0.96729955
- -0.42527003
- -0.13728581
- -0.19951426
- -0.03334045
- 0.0
- 0.0
- -0.07136651
- -0.08233919
- -0.07828858
- -0.05634629
- -0.00779833
- -0.03913545
- -0.00564098
- -0.10194684
- -0.50844231
- -1.2922584
- -2.72585757
- -4.55456569
- -6.03491048
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
omol_elem_refs:
- 0.0
- -0.49411610444892
- -2.89659207553303
- -7.4720802826895
- -14.66104864181136
- -24.64971154838295
- -37.84644148236497
- -54.59266299311384
- -75.07807639439064
- -99.74649603167501
- -128.94394674694914
- -162.25716866511135
- -200.05955014687078
- -242.34777949272933
- -289.3527197883213
- -341.24172093158836
- -398.09153248693065
- -460.12612944368607
- -527.5100419633112
- -599.8793399472972
- -677.5281570369908
- -760.5707557249713
- -849.2967175126828
- -943.8342095728076
- -1044.3562394075072
- -1150.9125687963183
- -1263.588984876023
- -1382.637104719387
- -1508.1895517124794
- -1640.3938632189152
- -1779.2975802336646
- -1924.7047354456045
- -2076.806191221612
- -2235.68746268031
- -2401.358555291375
- -2573.968455790188
- -2753.610930890667
- -24.02111491193831
- -30.62391983705538
- -38.14683295199241
- -46.81746066656193
- -56.7329547581876
- -68.01350564971516
- -80.62495423471279
- -94.70989740278115
- -110.3999665135758
- -127.79680857955367
- -146.8987516522958
- -167.71503194984385
- -190.06100706114935
- -214.20643153418035
- -240.1794569797554
- -267.9594717960598
- -297.66509939312664
- -329.3540437751595
- -20.06631323716388
- -25.3794116271745
- -31.3880537468367
- -474.91305922096916
- -516.8419689883073
- -561.2492697570143
- -608.2066351498856
- -657.8278809423615
- -710.1994198751883
- -765.5104301778764
- -824.2549148314927
- -884.8824904350067
- -947.91706045979
- -1014.882225412879
- -1084.9758804769706
- -1158.584246187726
- -1235.3424777172395
- -47.78066222897485
- -56.75599849168096
- -66.84342196536772
- -78.09128206652416
- -90.46803216038552
- -104.13887565609733
- -119.17067569663863
- -135.61835299815843
- -153.42835251398267
- -172.41889811628528
- -192.76344949536428
- -214.5469771216279
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
